### ISSUE TITLE
no release tags in repo

### ISSUE THREAD

**Issue by jhoblitt** [AlexCline/puppet-dirtree#1]
It's useful for  `rspect-puppet` tests that declare dependencies on other puppet modules via a git repo url in their `.fixtures.yml` file to have tags to refer to that match up with puppet forge release versions.  Do you have existing tags that could be pushed to github or would you be willing to add something like a `0.2.0` or `v0.2.0` tag the current `HEAD` of `master`?

**Comment by AlexCline** [comment]
I added a tag for v0.2.1 which includes some new non-breaking functionality.
